### ISSUE TITLE
Example code for manual calibration of K30 sensor using I2C with Raspberry Pi

### ISSUE THREAD

**Issue by unemittedWalrus** [co2meter-org/ExampleCode#56]
I am looking for a command I can send to the K30 sensor via I2C to initiate the manual calibration of the sensor, either zero or open air. I would also like to be able to disable the automatic calibration of the sensor

**Comment by co2meter** [comment]
@unemittedWalrus  are you using Python or C?

**Comment by unemittedWalrus** [comment]
@co2meter Python

**Comment by co2meter** [comment]
@unemittedWalrus there's a new [branch](https://github.com/co2meter-org/ExampleCode/tree/56-example-code-for-manual-calibration-of-k30-sensor-using-i2c-with-raspberry-pi) with a new folder for Senseair I2C and a new [file ](https://github.com/co2meter-org/ExampleCode/blob/56-example-code-for-manual-calibration-of-k30-sensor-using-i2c-with-raspberry-pi/Sensair/Senseair_RaspberryPi_I2C/senseair_meas_cal_i2c.py) for taking a measurement, doing a zero cal, or doing a background cal (400ppm).

Give that a go and let me now how it works out.  We'll merge it in to development if all is well.

**Comment by unemittedWalrus** [comment]
Hey, thank you! I tested the background calibration and that works great.

**Comment by rjmiller2543** [comment]
Glad we could help! I'll merge this into development
